config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :tours
  resources :bookings

  root "home#index"
  match "*unmatched", to: "application#render_404", via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :client
  belongs_to :tour

  validates :client_id, presence: { message: "must be selected" }
  validates :tour_id, presence: { message: "must be selected" }
  validate :booking_date_cannot_be_in_the_past

  def booking_date_cannot_be_in_the_past
    if booking_date.present? && booking_date < Date.today
      errors.add(:booking_date, "cannot be in the past")
    end
  end
end

app/models/client.rb
class Client < ApplicationRecord
  validates :name, presence: true, format: { with: /\A[А-Яа-яЁёA-Za-z\-]+\z/, message: "can only contain letters and hyphens" }
  validates :surname, presence: true, format: { with: /\A[А-Яа-яЁёA-Za-z\-]+\z/, message: "can only contain letters and hyphens" }
  validates :patronymic, format: { with: /\A[А-Яа-яЁёA-Za-z\-]+\z/, message: "can only contain letters and hyphens" }
  validates :name, format: { without: /\s/, message: "must not contain spaces" }
  validates :surname, format: { without: /\s/, message: "must not contain spaces" }
  validates :patronymic, format: { without: /\s/, message: "must not contain spaces" }
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP, message: "invalid email address" }, uniqueness: true
  validates :phone_number, presence: true, format: { with: /\A8\d{10}\z/, message: "must start with 8 and be followed by 10 digits" }, uniqueness: true

  has_many :bookings

  before_validation :capitalize_names

  private
  def capitalize_names
    self.name = format_name(name)
    self.surname = format_name(surname)
    self.patronymic = format_name(patronymic)
  end

  def format_name(name)
    return if name.blank?
    name.split("-").map(&:capitalize).join("-")
  end
end

app/models/tour.rb
class Tour < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 300 }
  validates :duration, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  rescue_from ActiveRecord::ConnectionNotEstablished do |exception|
    flash[:alert] = "Database connection error: #{exception.message}"
    redirect_to root_path
  end

  rescue_from ActiveRecord::RecordNotFound, with: :render_404 do |exception|
    flash[:alert] = "Record not found: #{exception.message}"
  end

  rescue_from ActionController::RoutingError, with: :render_404 do |exception|
    flash[:alert] = "Page not found: #{exception.message}"
  end

  def render_404
    respond_to do |format|
      format.html { render file: "#{Rails.root}/public/404.html", status: :not_found }
      format.all { render nothing: true, status: :not_found }
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]
  before_action :get_clients_and_tours, only: %i[ new edit ]

  def index
    @bookings = Booking.all
  end

  def show
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      redirect_to @booking
    else
      get_clients_and_tours
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @booking.update(booking_params)
      redirect_to @booking
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  private
  def set_booking
    @booking = Booking.find(params[:id])
  end

  def get_clients_and_tours
    @clients = Client.all
    @tours = Tour.all
  end

  def booking_params
    params.expect(booking: [ :client_id, :tour_id, :booking_date ])
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  def index
    @clients = Client.all
  end

  def show
    @client = Client.includes(:bookings).find(params[:id])
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to @client
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @client.update(client_params)
      redirect_to @client
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @client.destroy
    redirect_to clients_path
  end

  private
  def set_client
    @client = Client.find(params[:id])
  end

  def client_params
    params.expect(client: [ :name, :surname, :patronymic, :email, :phone_number ])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: %i[ show edit update destroy ]
  def index
    @tours = Tour.all
  end

  def show
  end

  def new
    @tour = Tour.new
  end

  def create
    @tour = Tour.new(tour_params)
    if @tour.save
      redirect_to @tour
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @tour.update(tour_params)
      redirect_to @tour
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @tour.destroy
    redirect_to tours_path
  end

  private
  def set_tour
    @tour = Tour.find(params[:id])
  end

  def tour_params
    params.require(:tour).permit(:name, :description, :duration, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/bookings/_form.html.erb
<%= form_with(model: @booking, local: true, html: { class: 'model-form' }) do |form| %>
  <div class="form-group">
    <%= form.label :client_id, "Client", class: 'form-label' %>
    <%= form.collection_select :client_id, @clients, :id, 
       lambda { |client| "#{client.surname} #{client.name.first}. #{client.patronymic.first}." }, 
       prompt: true, class: 'form-input' %>
    <% if @booking.errors[:client_id].any? %>
      <div class="error-message"><%= @booking.errors[:client_id].join(", ") %></div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :tour_id, "Tour", class: 'form-label' %>
    <%= form.collection_select :tour_id, @tours, :id, :name, prompt: true, class: 'form-input'  %>
    <% if @booking.errors[:tour_id].any? %>
      <div class="error-message"><%= @booking.errors[:tour_id].join(", ") %></div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :booking_date, class: 'form-label' %>
    <%= form.date_select :booking_date, class: 'form-input' %>
    <% if @booking.errors[:booking_date].any? %>
      <div class="error-message"><%= @booking.errors[:booking_date].join(", ") %></div>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: 'form-submit' %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Edit Booking</h1>

<%= render "form", booking: @booking%>
<%= link_to "Cancel", bookings_path, class: "button-link back-button"%>

app/views/bookings/index.html.erb
<h1 class="centered">Bookings</h1>

<div class="return-button-container">
    <%= link_to "Return", root_path, class: "button-link return-button" %>
</div>

<%= link_to "New booking", new_booking_path, class: "button-link" %>

<table>
    <thead>
        <tr>
            <th>Booking date</th>
            <th>Tour name</th>
            <th>Client initials</th>
        </tr>
    </thead>
    <tbody>
        <% @bookings.each do |booking| %>
        <tr>
            <td><%= booking.booking_date %></td>
            <td><%= booking.tour.name %></td>
            <td><%= "#{booking.client.surname} #{booking.client.name.first}. #{booking.client.patronymic.first}." %></td>
            <td><a href="/bookings/<%= booking.id %>">Show</td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render "form", booking: @booking%>
<%= link_to "Cancel", bookings_path, class: "button-link back-button" %>

app/views/bookings/show.html.erb
<h1>Booking Details</h1>

<div class="details">
  <ul>
    <li><strong>Booking date:</strong> <%= @booking.booking_date.strftime("%d %B %Y") %></li>
    <li><strong>Tour name:</strong> <%= link_to @booking.tour.name, tour_path(@booking.tour.id) %></li>
    <li><strong>Client Initials:</strong> <%= link_to "#{@booking.client.surname} #{@booking.client.name.first}. #{@booking.client.patronymic.first}.", client_path(@booking.client.id) %></li>
  </ul>
</div>

<div class="actions">
  <%= link_to "Edit", edit_booking_path(@booking), class: "button-link" %><br>
  <%= button_to "Delete", @booking, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "button-link"%>
  <%= link_to "Back", bookings_path, class: "button-link back-button" %>
</div>

app/views/clients/_form.html.erb
<%= form_with model: @client, html: { class: 'model-form' } do |form| %>
  <div class="form-group">
    <%= form.label :surname, class: 'form-label' %>
    <%= form.text_field :surname, class: 'form-input' %>
    <% if @client.errors[:surname].any? %>
      <div class="error-message"><%= @client.errors[:surname].join(", ") %></div>
    <% end %>
  </div>
  
  <div class="form-group">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-input' %>
    <% if @client.errors[:name].any? %>
      <div class="error-message"><%= @client.errors[:name].join(", ") %></div>
    <% end %>
  </div>
  
  <div class="form-group">
    <%= form.label :patronymic, class: 'form-label' %>
    <%= form.text_field :patronymic, class: 'form-input' %>
    <% if @client.errors[:patronymic].any? %>
      <div class="error-message"><%= @client.errors[:patronymic].join(", ") %></div>
    <% end %>
  </div>
  
  <div class="form-group">
    <%= form.label :email, class: 'form-label' %>
    <%= form.text_field :email, class: 'form-input' %>
    <% if @client.errors[:email].any? %>
      <div class="error-message"><%= @client.errors[:email].join(", ") %></div>
    <% end %>
  </div>
  
  <div class="form-group">
    <%= form.label :phone_number, class: 'form-label' %>
    <%= form.text_field :phone_number, class: 'form-input' %>
    <% if @client.errors[:phone_number].any? %>
      <div class="error-message"><%= @client.errors[:phone_number].join(", ") %></div>
    <% end %>
  </div>
  
  <div class="form-group">
    <%= form.submit 'Submit', class: 'form-submit' %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Edit Client</h1>

<%= render "form", client: @client%>
<%= link_to "Cancel", clients_path, class: "button-link back-button"%>

app/views/clients/index.html.erb
<h1 class="centered">Clients</h1>

<div class="return-button-container">
  <%= link_to "Return", root_path, class: "button-link return-button" %>
</div>

<%= link_to "New client", new_client_path, class: "button-link" %>

<table>
  <thead>
    <tr>
      <th>Surname</th>
      <th>Name</th>
      <th>Patronymic</th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.surname %></td>
        <td><%= client.name %></td>
        <td><%= client.patronymic %></td>
        <td><a href="/clients/<%= client.id %>">Show</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render "form", client: @client%>
<%= link_to "Cancel", clients_path, class: "button-link back-button" %>

app/views/clients/show.html.erb
<h1>Client Details</h1>

<div class="details">
    <ul>
        <li><strong>Name:</strong> <%= @client.name %></li>
        <li><strong>Surname:</strong> <%= @client.surname %></li>
        <li><strong>Patronymic:</strong> <%= @client.patronymic %></li>
        <li><strong>Email:</strong> <%= @client.email %></li>
        <li><strong>Phone Number:</strong> <%= @client.phone_number %></li>
    </ul>
</div>

<h2>Бронирования:</h2>
<div class="details">
    <ul>
        <% @client.bookings.each do |booking| %>
        <li>
            <%= link_to "#{booking.booking_date.strftime("%d %B %Y")} #{booking.tour.name}", booking_path(booking.tour.id) %>
        </li>
        <% end %>
    </ul>
</div>

<div class="actions">
    <%= link_to "Edit", edit_client_path(@client), class: "button-link" %><br>
    <%= button_to "Delete", @client, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "button-link"%>
    <%= link_to "Back", clients_path, class: "button-link back-button" %>
</div>

app/views/home/index.html.erb
<h1>Tours Agency</h1>
<p></p>

<div class="details centered">
  <ul>
    <li><%= link_to 'Clients', clients_path, class: "button-link" %></li>
    <li><%= link_to 'Tours', tours_path, class: "button-link" %></li>
    <li><%= link_to 'Bookings', bookings_path, class: "button-link" %></li>
  </ul>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Tours CRUD" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tours/_form.html.erb
<%= form_with model: @tour, html: { class: 'model-form' } do |form| %>
  <div class="form-group">
    <%= form.label :name, class: 'form-label'  %>
    <%= form.text_field :name, class: 'form-input' %>
    <% if @tour.errors[:name].any? %>
      <div class="error-message"><%= @tour.errors[:name].join(", ") %></div>
    <% end %>
  </div>
  <div class="form-group">
    <%= form.label :description, class: 'form-label'  %>
    <%= form.text_field :description, class: 'form-input' %>
    <% if @tour.errors[:description].any? %>
      <div class="error-message"><%= @tour.errors[:description].join(", ") %></div>
    <% end %>
  </div>
  <div class="form-group">
    <%= form.label :duration, class: 'form-label'  %>
    <%= form.text_field :duration, class: 'form-input' %>
    <% if @tour.errors[:duration].any? %>
      <div class="error-message"><%= @tour.errors[:duration].join(", ") %></div>
    <% end %>
  </div>
  <div class="form-group">
    <%= form.label :price, class: 'form-label'  %>
    <%= form.text_field :price, class: 'form-input' %>
    <% if @tour.errors[:price].any? %>
      <div class="error-message"><%= @tour.errors[:price].join(", ") %></div>
    <% end %>
  </div>
  <div class="form-group">
    <%= form.submit 'Submit', class: 'form-submit'  %>
  </div>
<% end %>

app/views/tours/edit.html.erb
<h1>Edit Tour</h1>

<%= render "form", tour: @tour%>
<%= link_to "Cancel", tours_path, class: "button-link back-button"%>

app/views/tours/index.html.erb
<h1 class="centered">Tours</h1>

<div class="return-button-container">
  <%= link_to "Return", root_path, class: "button-link return-button" %>
</div>

<%= link_to "New tour", new_tour_path, class: "button-link" %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Duration (days)</th>
    </tr>
  </thead>
  <tbody>
    <% @tours.each do |tour| %>
      <tr>
        <td><%= tour.name %></td>
        <td><%= tour.duration %></td>
        <td><a href="/tours/<%= tour.id %>">Show</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tours/new.html.erb
<h1>New Tour</h1>

<%= render "form", tour: @tour%>
<%= link_to "Cancel", tours_path, class: "button-link back-button" %>

app/views/tours/show.html.erb
<h1>Tour Details</h1>

<div class="details">
    <ul>
        <li><strong>Name:</strong> <%= @tour.name %></li>
        <li><strong>Description:</strong> <%= @tour.description %></li>
        <li><strong>Duration:</strong> <%= @tour.duration %> days</li>
        <li><strong>Price:</strong> <%= @tour.price %></li>
    </ul>
</div>

<div class="actions">
    <%= link_to "Edit", edit_tour_path(@tour), class: "button-link" %><br>
    <%= button_to "Delete", @tour, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "button-link"%>
    <%= link_to "Back", tours_path, class: "button-link back-button" %>
</div>